source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

target 'RxFSPagerView_Example' do
  pod 'RxFSPagerView', :path => '../'

  target 'RxFSPagerView_Tests' do
    inherit! :search_paths

    
  end
end
